{
 "title": "User Activity Tracking Dashboards",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Positive Request And With Error Endpoint",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (path,status)(user_activity_tracking_api_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Positive  Request Endpoint",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (path)(user_activity_tracking_api_requests_total) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total All Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(user_activity_tracking_api_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}